#!/usr/bin/env python3
"""drift_classify.py — Single source of truth for "is this path auto-generated drift?"

Drift = files that are produced deterministically by hooks/scheduled tasks
and never benefit from PR review (auto-counters, regenerated indexes, archived
logs, ingested raw summaries, dream/outcome records).

Code = files where a human reviewer adds value (skill bodies, hook scripts,
rules, configs, scripts, new content learnings written by /scribe).

Usage:
    python scripts/drift_classify.py path1 path2 ...
        exit 0 if ALL paths match drift allowlist
        exit 1 if ANY path is non-drift; non-drift paths printed to stderr

    git diff --name-only HEAD | python scripts/drift_classify.py -
        same, reading paths from stdin (newline-separated)

    python scripts/drift_classify.py --staged
        classifies currently staged files

Library use:
    from drift_classify import classify_paths
    all_drift, non_drift = classify_paths(["a.md", "b.json"])
"""
from __future__ import annotations

import argparse
import fnmatch
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

DRIFT_PATTERNS: tuple[str, ...] = (
    # Memory: hook-generated state and indexes
    ".claude/memory/concept-graph.json",
    ".claude/memory/daily-reports.md",
    ".claude/memory/news.md",
    ".claude/memory/news-archive.md",
    ".claude/memory/news-proposals.md",
    ".claude/memory/radar.md",
    ".claude/memory/radar-proposals.md",
    ".claude/memory/evolution-log.md",
    ".claude/memory/replay-queue.md",
    ".claude/memory/replay-queue-archive.md",
    ".claude/memory/improvement-log.md",
    ".claude/memory/improvement-queue.md",
    ".claude/memory/improvement-queue-archive.md",
    ".claude/memory/activity-log.md",
    ".claude/memory/activity-log-archive.md",
    ".claude/memory/budget.md",
    ".claude/memory/budget-archive.md",
    ".claude/memory/observations.jsonl",
    ".claude/memory/sessions.jsonl",
    ".claude/memory/corrections.jsonl",
    ".claude/memory/violations.jsonl",
    ".claude/memory/permission-log.md",
    ".claude/memory/permission-log-archive.md",
    ".claude/memory/permission-log-archive-*.md",
    ".claude/memory/alerts.md",
    # Brain (2BRAIN ingest pipeline)
    ".claude/memory/brain/inbox.md",
    ".claude/memory/brain/watchlist.md",
    ".claude/memory/brain/raw/*.md",
    ".claude/memory/brain/captures/*.md",
    # Dreams, outcomes, failures (per-run records)
    ".claude/memory/dreams/*.md",
    ".claude/memory/outcomes/*.md",
    ".claude/memory/outcomes/archive/*.md",
    ".claude/memory/failures/*.md",
    ".claude/memory/failures/archive/*.md",
    ".claude/memory/optstate/*.json",
    # Raw session traces and archives
    ".claude/memory/raw/*.md",
    ".claude/memory/raw/archive/*.md",
    ".claude/memory/intermediate/*.json",
    ".claude/memory/intermediate/*.md",
    ".claude/memory/intermediate/merge-candidates/*.md",
    # Learnings indexes (auto-generated by build-component-indexes.py)
    ".claude/memory/learnings/index-*.md",
    ".claude/memory/learnings/block-manifest.json",
    # Hook state files
    ".claude/hooks/*-state.json",
    ".claude/hooks/advisor-state.json",
    # Trace files
    ".traces/sessions/*.jsonl",
    ".traces/*.jsonl",
    # MCP audit reports (regenerated periodically)
    ".claude/memory/mcp-security-audit-report.md",
)

# Auto-managed YAML frontmatter fields. Diffs touching only these keys count as drift.
AUTO_MANAGED_FIELDS: tuple[str, ...] = (
    "uses",
    "successful_uses",
    "harmful_uses",
    "confidence",
    "impact_score",
    "maturity",
    "related",
    "supersedes",
    "valid_until",
    "last_used",
)


def _normalize(path: str) -> str:
    """Convert backslashes to forward slashes for cross-platform glob matching."""
    norm = path.replace("\\", "/")
    while norm.startswith("./"):
        norm = norm[2:]
    return norm


def matches_drift_pattern(path: str) -> bool:
    """True if path matches any allowlist glob."""
    norm = _normalize(path)
    return any(fnmatch.fnmatch(norm, pat) for pat in DRIFT_PATTERNS)


def _diff_for(path: str) -> str:
    """Return combined unstaged + staged diff for a tracked path, or empty string."""
    rc, _ = _git(["ls-files", "--error-unmatch", "--", path])
    if rc != 0:
        return ""
    rc1, diff1 = _git(["diff", "--no-color", "-U0", "--", path])
    rc2, diff2 = _git(["diff", "--no-color", "-U0", "--cached", "--", path])
    return (diff1 if rc1 == 0 else "") + (diff2 if rc2 == 0 else "")


def _diff_only_auto_fields(diff: str) -> bool:
    """True if every changed line is auto-managed field bump, list continuation, or whitespace."""
    for line in diff.splitlines():
        if not line or line[0] not in "+-":
            continue
        if line.startswith(("+++", "---")):
            continue
        body = line[1:].lstrip()
        if not body:
            continue
        if any(body.startswith(f"{f}:") for f in AUTO_MANAGED_FIELDS):
            continue
        if body.startswith("- "):  # list continuation
            continue
        return False
    return True


def is_auto_managed_learning(path: str) -> bool:
    """True if learning file diff only touches auto-managed YAML fields.

    Excludes index-*.md (already in allowlist) and critical-patterns.md
    (graduated rules need review). Untracked learning files are not drift —
    they go through /scribe → PR.
    """
    norm = _normalize(path)
    if not norm.startswith(".claude/memory/learnings/"):
        return False
    if not norm.endswith(".md"):
        return False
    if "/index-" in norm or norm.endswith("/critical-patterns.md"):
        return False

    rc, _ = _git(["ls-files", "--error-unmatch", "--", path])
    if rc != 0:
        return False  # untracked → review

    diff = _diff_for(path)
    if not diff:
        return True  # CRLF noise, no real change

    return _diff_only_auto_fields(diff)


def is_auto_managed_wiki(path: str) -> bool:
    """True if wiki article diff only touches frontmatter metadata
    (sources count, last_updated). Body changes go through PR.
    """
    norm = _normalize(path)
    if not norm.startswith(".claude/memory/wiki/"):
        return False
    if not norm.endswith(".md"):
        return False

    rc, _ = _git(["ls-files", "--error-unmatch", "--", path])
    if rc != 0:
        return False  # new wiki article → review

    diff = _diff_for(path)
    if not diff:
        return True

    # Allow `sources:` and `last_updated:` (wiki-specific auto fields)
    extra_fields = ("sources", "last_updated", "generated", "cluster")
    for line in diff.splitlines():
        if not line or line[0] not in "+-":
            continue
        if line.startswith(("+++", "---")):
            continue
        body = line[1:].lstrip()
        if not body:
            continue
        if any(body.startswith(f"{f}:") for f in (*AUTO_MANAGED_FIELDS, *extra_fields)):
            continue
        if body.startswith("- "):
            continue
        return False
    return True


def _git(args: list[str]) -> tuple[int, str]:
    """Run a git command in REPO_ROOT, return (rc, stdout)."""
    try:
        proc = subprocess.run(
            ["git", *args],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=10,
        )
        return proc.returncode, proc.stdout
    except (subprocess.TimeoutExpired, OSError):
        return 1, ""


def classify_path(path: str) -> bool:
    """True if path is drift."""
    if matches_drift_pattern(path):
        return True
    if is_auto_managed_learning(path):
        return True
    if is_auto_managed_wiki(path):
        return True
    return False


def classify_paths(paths: list[str]) -> tuple[bool, list[str]]:
    """Return (all_drift, non_drift_paths)."""
    non_drift = [p for p in paths if p and not classify_path(p)]
    return (len(non_drift) == 0 and len(paths) > 0, non_drift)


def collect_paths(args: argparse.Namespace) -> list[str]:
    if args.staged:
        rc, out = _git(["diff", "--name-only", "--cached"])
        return [line for line in out.splitlines() if line.strip()] if rc == 0 else []
    if args.paths == ["-"]:
        return [line.strip() for line in sys.stdin if line.strip()]
    return [p for p in args.paths if p.strip()]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Classify paths as drift or non-drift.")
    parser.add_argument(
        "paths",
        nargs="*",
        help="Paths to classify, or '-' to read from stdin (newline-separated).",
    )
    parser.add_argument(
        "--staged",
        action="store_true",
        help="Classify currently staged files (git diff --cached).",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress 'all drift' success message.",
    )
    args = parser.parse_args(argv)

    paths = collect_paths(args)
    if not paths:
        print("drift-classify: no paths supplied", file=sys.stderr)
        return 2

    all_drift, non_drift = classify_paths(paths)

    if non_drift:
        print(
            f"drift-classify: {len(non_drift)} non-drift path(s) — review required:",
            file=sys.stderr,
        )
        for p in non_drift:
            print(f"  {p}", file=sys.stderr)
        return 1

    if not args.quiet:
        print(
            f"drift-classify: all {len(paths)} path(s) are drift — "
            f"safe to commit direct to main"
        )
    return 0


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, OSError):
        pass
    sys.exit(main())
