"""Regenerate auto-managed sections of CLAUDE.md from project profiles.

Sections marked with `<!-- AUTO:<name>:start -->` ... `<!-- AUTO:<name>:end -->`
are regenerated. Manually-written content outside markers is preserved.

Sources:
- `~/.claude/memory/projects/*.yaml` — project profiles (name, priority, type)

Sections regenerated:
- `projects` — table of distribution targets

Usage:
    python scripts/regen-claude-md.py             # dry-run (prints diff)
    python scripts/regen-claude-md.py --write     # apply changes in place
    python scripts/regen-claude-md.py --check     # exit 1 if regen would change anything

Excluded from `projects` table:
- stopa.yaml — STOPA is the source, not a target
- terminology-db.yaml — infrastructure, not a target project
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

import yaml

# UTF-8 stdout for Windows
if sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[1]
CLAUDE_MD = REPO_ROOT / "CLAUDE.md"
PROFILES_DIR = Path.home() / ".claude" / "memory" / "projects"

EXCLUDE_FROM_PROJECTS = {"stopa.yaml", "terminology-db.yaml"}

PRIORITY_ORDER = {"high": 0, "medium": 1, "low": 2}

MARKER_RE = re.compile(
    r"<!-- AUTO:(?P<name>[a-z0-9_-]+):start -->.*?<!-- AUTO:(?P=name):end -->",
    re.DOTALL,
)


def load_projects() -> list[dict]:
    """Read all project YAMLs except excluded ones, return list of dicts."""
    if not PROFILES_DIR.exists():
        raise FileNotFoundError(f"Project profiles dir not found: {PROFILES_DIR}")

    projects = []
    for yaml_path in sorted(PROFILES_DIR.glob("*.yaml")):
        if yaml_path.name in EXCLUDE_FROM_PROJECTS:
            continue
        with yaml_path.open(encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        if not data.get("name") or not data.get("priority"):
            continue
        projects.append({
            "name": data["name"],
            "type": data.get("type", "—"),
            "priority": data.get("priority", "low"),
        })
    return projects


def render_projects_section(projects: list[dict]) -> str:
    """Generate markdown table sorted by priority then name."""
    sorted_projects = sorted(
        projects,
        key=lambda p: (PRIORITY_ORDER.get(p["priority"], 99), p["name"]),
    )
    lines = [
        "<!-- AUTO:projects:start -->",
        "<!-- Generated by scripts/regen-claude-md.py — do not edit manually. -->",
        "<!-- Source: ~/.claude/memory/projects/*.yaml -->",
        "",
        "| Projekt | Typ | Priorita |",
        "|---------|-----|----------|",
    ]
    for p in sorted_projects:
        lines.append(f"| **{p['name']}** | {p['type']} | {p['priority']} |")
    lines.append("<!-- AUTO:projects:end -->")
    return "\n".join(lines)


def replace_section(content: str, section_name: str, new_block: str) -> str:
    """Replace the marker block named `section_name` with `new_block`.

    Raises ValueError if markers for `section_name` are not present in content.
    """
    pattern = re.compile(
        rf"<!-- AUTO:{re.escape(section_name)}:start -->.*?<!-- AUTO:{re.escape(section_name)}:end -->",
        re.DOTALL,
    )
    if not pattern.search(content):
        raise ValueError(
            f"Markers <!-- AUTO:{section_name}:start --> ... <!-- AUTO:{section_name}:end --> "
            f"not found in CLAUDE.md. Add them around the section to make it auto-managed."
        )
    return pattern.sub(new_block, content)


def regenerate(content: str) -> str:
    """Apply all auto sections to content."""
    projects = load_projects()
    block = render_projects_section(projects)
    return replace_section(content, "projects", block)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--write", action="store_true", help="Apply changes in place")
    parser.add_argument("--check", action="store_true", help="Exit 1 if changes needed")
    args = parser.parse_args()

    if not CLAUDE_MD.exists():
        print(f"ERROR: {CLAUDE_MD} not found", file=sys.stderr)
        return 2

    original = CLAUDE_MD.read_text(encoding="utf-8")
    try:
        regenerated = regenerate(original)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    if original == regenerated:
        print("CLAUDE.md is up to date — no changes.")
        return 0

    if args.check:
        print("CLAUDE.md is out of date. Run with --write to regenerate.", file=sys.stderr)
        diff = difflib.unified_diff(
            original.splitlines(keepends=True),
            regenerated.splitlines(keepends=True),
            fromfile="CLAUDE.md (current)",
            tofile="CLAUDE.md (regenerated)",
            n=3,
        )
        sys.stderr.writelines(diff)
        return 1

    if args.write:
        CLAUDE_MD.write_text(regenerated, encoding="utf-8")
        print(f"Wrote regenerated CLAUDE.md ({len(regenerated)} bytes).")
        return 0

    # dry-run default
    diff = list(
        difflib.unified_diff(
            original.splitlines(keepends=True),
            regenerated.splitlines(keepends=True),
            fromfile="CLAUDE.md (current)",
            tofile="CLAUDE.md (regenerated)",
            n=3,
        )
    )
    print("Dry-run diff (use --write to apply):\n")
    sys.stdout.writelines(diff)
    return 0


if __name__ == "__main__":
    sys.exit(main())
